# Generated by Django 4.0.2 on 2022-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='name',
            field=models.TextField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
